### ISSUE TITLE
Crashes due to missing workspace settings

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-volar#45] opened 2021-10-28 14:51 UTC
Just for fun I've tried to run the v1.0.5 release on Vue 2 project and got:

```
:: <-- LSP-volar workspace/configuration(6): {'items': [{'scopeUri': 'file:///Users/test.vue.html', 'section': 'html.hover'}]}
:: >>> LSP-volar 6: [None]
LSP-volar: /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-html-languageservice/lib/umd/languageFacts/dataProvider.js:104
LSP-volar:         if (item.description && settings.documentation !== false) {
LSP-volar:                                          ^
LSP-volar: 
LSP-volar: TypeError: Cannot read property 'documentation' of null
LSP-volar:     at generateDocumentation (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-html-languageservice/lib/umd/languageFacts/dataProvider.js:104:42)
LSP-volar:     at /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-html-languageservice/lib/umd/services/htmlHover.js:45:90
LSP-volar:     at Array.forEach (<anonymous>)
LSP-volar:     at _loop_1 (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-html-languageservice/lib/umd/services/htmlHover.js:43:44)
LSP-volar:     at getTagHover (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-html-languageservice/lib/umd/services/htmlHover.js:62:35)
LSP-volar:     at HTMLHover.doHover (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-html-languageservice/lib/umd/services/htmlHover.js:213:24)
LSP-volar:     at onHtml (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-vue-languageservice/out/services/hover.js:88:30)
LSP-volar:     at async Object.<anonymous> (/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.2.0/server/node_modules/vscode-vue-languageservice/out/services/hover.js:13:28)
```

Looks like we should define the `settings` section with relevant settings.

**Comment by johnsoncodehk** [comment] 2021-11-10 12:57
This problem should be resolved by https://github.com/johnsoncodehk/volar/pull/678.

**Comment by rchl** [comment] 2021-11-10 13:44
Thanks.

I think it also makes sense for us to clean up stuff here. We are currently passing all options through `intializationOptions` and probably we should do that instead through workspace options.

Since you are the volar developer, maybe you can explain what is expected? Do we need to define those in both places or in `setttings` would be enough? Or somewhere in between?

**Comment by johnsoncodehk** [comment] 2021-11-10 14:21
The problem is that `vscode-html-languageservice` expected options is undefined or object, but got null from LSP.

For language server null (or undefined) is good, I think language server is responsible to handling.

**Comment by rchl** [comment] 2021-11-10 15:28
Yes, but what I'm asking is what's the preferred way for the volar server to receive the settings.

Through the `initialize` request's `initializationOptions` or through the `workspace/didChangeConfiguration` / `workspace/configuration`.

**Comment by johnsoncodehk** [comment] 2021-11-10 16:48
Volar gives priority to using `workspace/didChangeConfiguration` / `workspace/configuration`, and for special needs, `initializationOptions` will be used.

For example, for tab name casing / attr name casing, volar supports documents to be set separately in its own status bar. The language server needs to query the language client for the name casing of each document, so it needs to use `initializationOptions` + language client request.

For `html.hover` settings, since it is the VSCode HTML extension's agreed settings, volar is always handled as `workspace/didChangeConfiguration` / `workspace/configuration`.

**Comment by predragnikolic** [comment] 2021-11-28 13:17
The reported issue has been fixed, so I will close it.

**Closed by predragnikolic** 2021-11-28 13:17 UTC
